
package Main;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;

public class Pantalla extends javax.swing.JFrame {

    private final Paso paso;
    private boolean parado;
    
    public Pantalla(Paso paso) {
        this.paso = paso;
        parado = false;
        initComponents();
    }

    public JTextField getAeroviaBMTextField() {return AeroviaBMTextField;}
    public JTextField getAeroviaMBTextField() {return AeroviaMBTextField;}
    public JTextField getEstacionamientoTextFieldB() {return EstacionamientoTextFieldB;}
    public JTextField getEstacionamientoTextFieldM() {return EstacionamientoTextFieldM;}
    public JTextField getGate1TextFieldB() {return Gate1TextFieldB;}
    public JTextField getGate1TextFieldM() {return Gate1TextFieldM;}
    public JTextField getGate2TextFieldB() {return Gate2TextFieldB;}
    public JTextField getGate2TextFieldM() {return Gate2TextFieldM;}
    public JTextField getGate3TextFieldB() {return Gate3TextFieldB;}
    public JTextField getGate3TextFieldM() {return Gate3TextFieldM;}
    public JTextField getGate4TextFieldB() {return Gate4TextFieldB;}
    public JTextField getGate4TextFieldM() {return Gate4TextFieldM;}
    public JTextField getGate5TextFieldB() {return Gate5TextFieldB;}
    public JTextField getGate5TextFieldM() {return Gate5TextFieldM;}
    public JTextField getGate6TextFieldB() {return Gate6TextFieldB;}
    public JTextField getGate6TextFieldM() {return Gate6TextFieldM;}
    public JTextField getHangarTextFieldB() {return HangarTextFieldB;}
    public JTextField getHangarTextFieldM() {return HangarTextFieldM;}
    public JTextField getPasajerosTextFieldB() {return PasajerosTextFieldB;}
    public JTextField getPasajerosTextFieldM() {return PasajerosTextFieldM;}
    public JTextField getPista1TextFieldB() {return Pista1TextFieldB;}
    public JTextField getPista1TextFieldM() {return Pista1TextFieldM;}
    public JTextField getPista2TextFieldB() {return Pista2TextFieldB;}
    public JTextField getPista2TextFieldM() {return Pista2TextFieldM;}
    public JTextField getPista3TextFieldB() {return Pista3TextFieldB;}
    public JTextField getPista3TextFieldM() {return Pista3TextFieldM;}
    public JTextField getPista4TextFieldB() {return Pista4TextFieldB;}
    public JTextField getPista4TextFieldM() {return Pista4TextFieldM;}
    public JTextField getRodajeTextFieldB() {return RodajeTextFieldB;}
    public JTextField getRodajeTextFieldM() {return RodajeTextFieldM;}
    public JTextField getTallerTextFieldB() {return TallerTextFieldB;}
    public JTextField getTallerTextFieldM() {return TallerTextFieldM;}
    public JTextField getTransferAeropuertoTextFieldB() {return TransferAeropuertoTextFieldB;}
    public JTextField getTransferAeropuertoTextFieldM() {return TransferAeropuertoTextFieldM;}
    public JTextField getTransferCiudadTextFieldB() {return TransferCiudadTextFieldB;}
    public JTextField getTransferCiudadTextFieldM() {return TransferCiudadTextFieldM;}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel36 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jTextField32 = new javax.swing.JTextField();
        jTextField35 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jTextField40 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextField39 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField34 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField33 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jTextField37 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField38 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jTextField36 = new javax.swing.JTextField();
        BotonParar = new javax.swing.JButton();
        BotonReanudar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TransferAeropuertoTextFieldM = new javax.swing.JTextField();
        TransferCiudadTextFieldM = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        PasajerosTextFieldM = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        HangarTextFieldM = new javax.swing.JTextField();
        TallerTextFieldM = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        EstacionamientoTextFieldM = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Gate1TextFieldM = new javax.swing.JTextField();
        Gate2TextFieldM = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Gate3TextFieldM = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        Gate4TextFieldM = new javax.swing.JTextField();
        Gate5TextFieldM = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Gate6TextFieldM = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        RodajeTextFieldM = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        Pista1TextFieldM = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        Pista2TextFieldM = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        Pista3TextFieldM = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        Pista4TextFieldM = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        Gate6TextFieldB = new javax.swing.JTextField();
        TransferAeropuertoTextFieldB = new javax.swing.JTextField();
        TransferCiudadTextFieldB = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        PasajerosTextFieldB = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        RodajeTextFieldB = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        HangarTextFieldB = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        TallerTextFieldB = new javax.swing.JTextField();
        Pista1TextFieldB = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        Pista2TextFieldB = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        EstacionamientoTextFieldB = new javax.swing.JTextField();
        Pista3TextFieldB = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        Pista4TextFieldB = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        Gate1TextFieldB = new javax.swing.JTextField();
        Gate2TextFieldB = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        Gate3TextFieldB = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        Gate4TextFieldB = new javax.swing.JTextField();
        Gate5TextFieldB = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AeroviaMBTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        AeroviaBMTextField = new javax.swing.JTextField();

        jLabel36.setText("Pista 4:");

        jLabel35.setText("Pista 3:");

        jLabel41.setText("Gate 4:");

        jTextField40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField40ActionPerformed(evt);
            }
        });

        jTextField21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField21ActionPerformed(evt);
            }
        });

        jLabel28.setText("Área Rodaje:");

        jTextField39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField39ActionPerformed(evt);
            }
        });

        jLabel33.setText("Pista 1:");

        jLabel26.setText("Gate 1:");

        jLabel25.setText("Área Estacionamiento: ");

        jTextField22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField22ActionPerformed(evt);
            }
        });

        jLabel24.setText("Taller:");

        jTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField20ActionPerformed(evt);
            }
        });

        jLabel39.setText("Transfers Aeropuerto:");

        jLabel22.setText("Nº de pasageros en el aeropuerto: ");

        jTextField33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField33ActionPerformed(evt);
            }
        });

        jLabel23.setText("Hangar:");

        jLabel37.setText("Gate 2:");

        jLabel42.setText("Gate 5:");

        jTextField23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField23ActionPerformed(evt);
            }
        });

        jLabel40.setText("Transfers Ciudad:");

        jTextField37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField37ActionPerformed(evt);
            }
        });

        jTextField38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField38ActionPerformed(evt);
            }
        });

        jLabel21.setText("Gate 6:");

        jTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField19ActionPerformed(evt);
            }
        });

        jLabel38.setText("Gate 3:");

        jLabel34.setText("Pista 2:");

        jTextField36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField36ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        BotonParar.setText("Parar");
        BotonParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPararActionPerformed(evt);
            }
        });

        BotonReanudar.setText("Reanudar");
        BotonReanudar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonReanudarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Aeropuerto de Madrid");

        jLabel3.setText("Transfers Aeropuerto:");

        jLabel4.setText("Transfers Ciudad:");

        TransferAeropuertoTextFieldM.setEditable(false);
        TransferAeropuertoTextFieldM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransferAeropuertoTextFieldMActionPerformed(evt);
            }
        });

        TransferCiudadTextFieldM.setEditable(false);
        TransferCiudadTextFieldM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransferCiudadTextFieldMActionPerformed(evt);
            }
        });

        jLabel7.setText("Nº de pasajeros en el aeropuerto: ");

        PasajerosTextFieldM.setEditable(false);
        PasajerosTextFieldM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasajerosTextFieldMActionPerformed(evt);
            }
        });

        jLabel9.setText("Hangar:");

        jLabel10.setText("Taller:");

        HangarTextFieldM.setEditable(false);
        HangarTextFieldM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HangarTextFieldMActionPerformed(evt);
            }
        });

        TallerTextFieldM.setEditable(false);

        jLabel13.setText("Área Estacionamiento: ");

        EstacionamientoTextFieldM.setEditable(false);
        EstacionamientoTextFieldM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstacionamientoTextFieldMActionPerformed(evt);
            }
        });

        jLabel15.setText("Gate 1:");

        Gate1TextFieldM.setEditable(false);
        Gate1TextFieldM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gate1TextFieldMActionPerformed(evt);
            }
        });

        Gate2TextFieldM.setEditable(false);
        Gate2TextFieldM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gate2TextFieldMActionPerformed(evt);
            }
        });

        jLabel16.setText("Gate 2:");

        jLabel17.setText("Gate 3:");

        Gate3TextFieldM.setEditable(false);
        Gate3TextFieldM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gate3TextFieldMActionPerformed(evt);
            }
        });

        jLabel18.setText("Gate 4:");

        Gate4TextFieldM.setEditable(false);
        Gate4TextFieldM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gate4TextFieldMActionPerformed(evt);
            }
        });

        Gate5TextFieldM.setEditable(false);
        Gate5TextFieldM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gate5TextFieldMActionPerformed(evt);
            }
        });

        jLabel19.setText("Gate 5:");

        jLabel20.setText("Gate 6:");

        Gate6TextFieldM.setEditable(false);
        Gate6TextFieldM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gate6TextFieldMActionPerformed(evt);
            }
        });

        jLabel27.setText("Área Rodaje:");

        RodajeTextFieldM.setEditable(false);
        RodajeTextFieldM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RodajeTextFieldMActionPerformed(evt);
            }
        });

        jLabel29.setText("Pista 1:");

        Pista1TextFieldM.setEditable(false);

        jLabel30.setText("Pista 2:");

        Pista2TextFieldM.setEditable(false);

        jLabel31.setText("Pista 3:");

        Pista3TextFieldM.setEditable(false);

        jLabel32.setText("Pista 4:");

        Pista4TextFieldM.setEditable(false);

        jLabel43.setText("Gate 6:");

        Gate6TextFieldB.setEditable(false);
        Gate6TextFieldB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gate6TextFieldBActionPerformed(evt);
            }
        });

        TransferAeropuertoTextFieldB.setEditable(false);
        TransferAeropuertoTextFieldB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransferAeropuertoTextFieldBActionPerformed(evt);
            }
        });

        TransferCiudadTextFieldB.setEditable(false);
        TransferCiudadTextFieldB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransferCiudadTextFieldBActionPerformed(evt);
            }
        });

        jLabel44.setText("Nº de pasageros en el aeropuerto: ");

        PasajerosTextFieldB.setEditable(false);
        PasajerosTextFieldB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasajerosTextFieldBActionPerformed(evt);
            }
        });

        jLabel45.setText("Área Rodaje:");

        RodajeTextFieldB.setEditable(false);

        jLabel46.setText("Hangar:");

        jLabel47.setText("Taller:");

        HangarTextFieldB.setEditable(false);
        HangarTextFieldB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HangarTextFieldBActionPerformed(evt);
            }
        });

        jLabel48.setText("Pista 1:");

        TallerTextFieldB.setEditable(false);

        Pista1TextFieldB.setEditable(false);

        jLabel49.setText("Pista 2:");

        Pista2TextFieldB.setEditable(false);

        jLabel50.setText("Área Estacionamiento: ");

        jLabel51.setText("Pista 3:");

        EstacionamientoTextFieldB.setEditable(false);
        EstacionamientoTextFieldB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstacionamientoTextFieldBActionPerformed(evt);
            }
        });

        Pista3TextFieldB.setEditable(false);

        jLabel52.setText("Pista 4:");

        Pista4TextFieldB.setEditable(false);

        jLabel53.setText("Gate 1:");

        Gate1TextFieldB.setEditable(false);
        Gate1TextFieldB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gate1TextFieldBActionPerformed(evt);
            }
        });

        Gate2TextFieldB.setEditable(false);
        Gate2TextFieldB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gate2TextFieldBActionPerformed(evt);
            }
        });

        jLabel54.setText("Gate 2:");

        jLabel55.setText("Gate 3:");

        Gate3TextFieldB.setEditable(false);
        Gate3TextFieldB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gate3TextFieldBActionPerformed(evt);
            }
        });

        jLabel56.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel56.setText("Aeropuerto de Barcelona");

        jLabel57.setText("Transfers Aeropuerto:");

        jLabel58.setText("Transfers Ciudad:");

        jLabel59.setText("Gate 4:");

        Gate4TextFieldB.setEditable(false);
        Gate4TextFieldB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gate4TextFieldBActionPerformed(evt);
            }
        });

        Gate5TextFieldB.setEditable(false);
        Gate5TextFieldB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gate5TextFieldBActionPerformed(evt);
            }
        });

        jLabel60.setText("Gate 5:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Aeriovía Madird-Barcelona");

        AeroviaMBTextField.setEditable(false);
        AeroviaMBTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AeroviaMBTextFieldActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Aeriovía Barcelona-Madrid");

        AeroviaBMTextField.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AeroviaMBTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AeroviaBMTextField, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(BotonParar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Pista1TextFieldM, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Pista2TextFieldM, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Pista4TextFieldM))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Pista3TextFieldM, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Gate1TextFieldM))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Gate2TextFieldM))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Gate3TextFieldM, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Gate4TextFieldM))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Gate5TextFieldM))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Gate6TextFieldM, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(18, 18, 18)
                                        .addComponent(EstacionamientoTextFieldM))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TransferAeropuertoTextFieldM, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TransferCiudadTextFieldM, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(PasajerosTextFieldM))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(TallerTextFieldM))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(HangarTextFieldM))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel27)
                                        .addGap(18, 18, 18)
                                        .addComponent(RodajeTextFieldM))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel56, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Pista1TextFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Pista2TextFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Pista3TextFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Pista4TextFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel45)
                                        .addGap(18, 18, 18)
                                        .addComponent(RodajeTextFieldB))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Gate1TextFieldB))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Gate2TextFieldB))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Gate3TextFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Gate6TextFieldB))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Gate5TextFieldB))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Gate4TextFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel50)
                                        .addGap(18, 18, 18)
                                        .addComponent(EstacionamientoTextFieldB))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel47)
                                        .addGap(18, 18, 18)
                                        .addComponent(TallerTextFieldB))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel46)
                                        .addGap(18, 18, 18)
                                        .addComponent(HangarTextFieldB))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(PasajerosTextFieldB))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel57, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TransferAeropuertoTextFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel58, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TransferCiudadTextFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(11, 11, 11))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotonReanudar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonReanudar)
                    .addComponent(BotonParar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(TransferAeropuertoTextFieldM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TransferCiudadTextFieldM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(PasajerosTextFieldM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(HangarTextFieldM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(TallerTextFieldM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(EstacionamientoTextFieldM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(Gate1TextFieldM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(Gate2TextFieldM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(Gate3TextFieldM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(Gate4TextFieldM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(Gate5TextFieldM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(Gate6TextFieldM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(RodajeTextFieldM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel29)
                                    .addComponent(Pista1TextFieldM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel30)
                                    .addComponent(Pista2TextFieldM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel31)
                                    .addComponent(Pista3TextFieldM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel32)
                                    .addComponent(Pista4TextFieldM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel56)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel57)
                            .addComponent(jLabel58)
                            .addComponent(TransferAeropuertoTextFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TransferCiudadTextFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel44)
                            .addComponent(PasajerosTextFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel46)
                            .addComponent(HangarTextFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel47)
                            .addComponent(TallerTextFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel50)
                            .addComponent(EstacionamientoTextFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel53)
                                    .addComponent(Gate1TextFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel54)
                                    .addComponent(Gate2TextFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel55)
                                    .addComponent(Gate3TextFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel59)
                                    .addComponent(Gate4TextFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel60)
                                    .addComponent(Gate5TextFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel43)
                                    .addComponent(Gate6TextFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel45)
                            .addComponent(RodajeTextFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel48)
                                    .addComponent(Pista1TextFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel49)
                                    .addComponent(Pista2TextFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel51)
                                    .addComponent(Pista3TextFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel52)
                                    .addComponent(Pista4TextFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AeroviaMBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AeroviaBMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPararActionPerformed
        /*escritor.escribir("SISTEMA DETENIDO");*/
        paso.cerrar();
        parado = true;
    }//GEN-LAST:event_BotonPararActionPerformed

    private void BotonReanudarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonReanudarActionPerformed
        /*escritor.escribir("SISTEMA REANUDADO");*/
        paso.abrir();
        parado = false;
    }//GEN-LAST:event_BotonReanudarActionPerformed

    private void TransferAeropuertoTextFieldMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransferAeropuertoTextFieldMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TransferAeropuertoTextFieldMActionPerformed

    private void TransferCiudadTextFieldMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransferCiudadTextFieldMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TransferCiudadTextFieldMActionPerformed

    private void PasajerosTextFieldMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasajerosTextFieldMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasajerosTextFieldMActionPerformed

    private void HangarTextFieldMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HangarTextFieldMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HangarTextFieldMActionPerformed

    private void EstacionamientoTextFieldMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstacionamientoTextFieldMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstacionamientoTextFieldMActionPerformed

    private void Gate1TextFieldMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gate1TextFieldMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Gate1TextFieldMActionPerformed

    private void Gate2TextFieldMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gate2TextFieldMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Gate2TextFieldMActionPerformed

    private void Gate3TextFieldMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gate3TextFieldMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Gate3TextFieldMActionPerformed

    private void Gate4TextFieldMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gate4TextFieldMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Gate4TextFieldMActionPerformed

    private void Gate5TextFieldMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gate5TextFieldMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Gate5TextFieldMActionPerformed

    private void Gate6TextFieldMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gate6TextFieldMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Gate6TextFieldMActionPerformed

    private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19ActionPerformed

    private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20ActionPerformed

    private void jTextField21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField21ActionPerformed

    private void jTextField22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField22ActionPerformed

    private void jTextField23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField23ActionPerformed

    private void jTextField33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField33ActionPerformed

    private void jTextField36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField36ActionPerformed

    private void jTextField37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField37ActionPerformed

    private void jTextField38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField38ActionPerformed

    private void jTextField39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField39ActionPerformed

    private void jTextField40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField40ActionPerformed

    private void Gate6TextFieldBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gate6TextFieldBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Gate6TextFieldBActionPerformed

    private void TransferAeropuertoTextFieldBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransferAeropuertoTextFieldBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TransferAeropuertoTextFieldBActionPerformed

    private void TransferCiudadTextFieldBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransferCiudadTextFieldBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TransferCiudadTextFieldBActionPerformed

    private void PasajerosTextFieldBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasajerosTextFieldBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasajerosTextFieldBActionPerformed

    private void HangarTextFieldBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HangarTextFieldBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HangarTextFieldBActionPerformed

    private void EstacionamientoTextFieldBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstacionamientoTextFieldBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstacionamientoTextFieldBActionPerformed

    private void Gate1TextFieldBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gate1TextFieldBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Gate1TextFieldBActionPerformed

    private void Gate2TextFieldBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gate2TextFieldBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Gate2TextFieldBActionPerformed

    private void Gate3TextFieldBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gate3TextFieldBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Gate3TextFieldBActionPerformed

    private void Gate4TextFieldBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gate4TextFieldBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Gate4TextFieldBActionPerformed

    private void Gate5TextFieldBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gate5TextFieldBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Gate5TextFieldBActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        /*escritor.cerrarEscritor();*/
    }//GEN-LAST:event_formWindowClosing

    private void RodajeTextFieldMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RodajeTextFieldMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RodajeTextFieldMActionPerformed

    private void AeroviaMBTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AeroviaMBTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AeroviaMBTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AeroviaBMTextField;
    private javax.swing.JTextField AeroviaMBTextField;
    private javax.swing.JButton BotonParar;
    private javax.swing.JButton BotonReanudar;
    private javax.swing.JTextField EstacionamientoTextFieldB;
    private javax.swing.JTextField EstacionamientoTextFieldM;
    private javax.swing.JTextField Gate1TextFieldB;
    private javax.swing.JTextField Gate1TextFieldM;
    private javax.swing.JTextField Gate2TextFieldB;
    private javax.swing.JTextField Gate2TextFieldM;
    private javax.swing.JTextField Gate3TextFieldB;
    private javax.swing.JTextField Gate3TextFieldM;
    private javax.swing.JTextField Gate4TextFieldB;
    private javax.swing.JTextField Gate4TextFieldM;
    private javax.swing.JTextField Gate5TextFieldB;
    private javax.swing.JTextField Gate5TextFieldM;
    private javax.swing.JTextField Gate6TextFieldB;
    private javax.swing.JTextField Gate6TextFieldM;
    private javax.swing.JTextField HangarTextFieldB;
    private javax.swing.JTextField HangarTextFieldM;
    private javax.swing.JTextField PasajerosTextFieldB;
    private javax.swing.JTextField PasajerosTextFieldM;
    private javax.swing.JTextField Pista1TextFieldB;
    private javax.swing.JTextField Pista1TextFieldM;
    private javax.swing.JTextField Pista2TextFieldB;
    private javax.swing.JTextField Pista2TextFieldM;
    private javax.swing.JTextField Pista3TextFieldB;
    private javax.swing.JTextField Pista3TextFieldM;
    private javax.swing.JTextField Pista4TextFieldB;
    private javax.swing.JTextField Pista4TextFieldM;
    private javax.swing.JTextField RodajeTextFieldB;
    private javax.swing.JTextField RodajeTextFieldM;
    private javax.swing.JTextField TallerTextFieldB;
    private javax.swing.JTextField TallerTextFieldM;
    private javax.swing.JTextField TransferAeropuertoTextFieldB;
    private javax.swing.JTextField TransferAeropuertoTextFieldM;
    private javax.swing.JTextField TransferCiudadTextFieldB;
    private javax.swing.JTextField TransferCiudadTextFieldM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField40;
    // End of variables declaration//GEN-END:variables
}
